config/routes.rb
Tq::Application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations"
  }  

  resources :users, :only => [:index, :edit, :update, :destroy]
  resources :questions
  resources :suggestions, :only => [:index, :create]
  resources :suggestions do
    post 'vote', to: 'suggestions#vote'
    post 'toggle_archive', to: 'suggestions#toggle_archive'
  end
  get '/about', to: 'static_pages#about'
  get '/admin_dashboard', to: 'admin_dashboard#dashboard'
  get '/admin_answers', to: 'answers#admin_answers'
  post '/email_question', to: 'admin_dashboard#email_question'
  post '/email_answers', to: 'admin_dashboard#email_answers'
  post '/post_answers', to: 'questions#release'
  get '/silly_title', to: 'sillytitles#new'
  get '/scoreboard', to: 'users#scoreboard'
  post '/reset_password', to: 'users#reset_password'

  resources :answers do
    post 'vote', to: 'answers#vote'
    resources :comments, :only => [:create, :destroy, :update]
  end
  resources :feed_items, :only => :update

  root :to => 'questions#today'
end

app/controllers/admin_dashboard_controller.rb
class AdminDashboardController < ApplicationController
  before_filter :admin_user

  def dashboard
  end

  def answers
  end

  def email_answers
    unless Question.todays_question.emailed_answers
      User.where(:receives_email => true).each do |user|
         Notifier.email_answers(user).deliver if user.receives_email
      end
      Question.todays_question.update_attributes(:emailed_answers => true)
      redirect_to admin_dashboard_path
    else
      flash[:alert] = 'You already sent out the answers!'
      redirect_to admin_dashboard_path
    end
  end
end

app/views/admin_dashboard/dashboard.html.erb
<div class="row container bigbox">
  <div class="span4 left-span-content">
      <h1>Admin Panel.</h1>
  </div>

  <div class="span7">
    <ul class="users">
      <li>
        <% if Question.question_posted? &&
              Question.todays_answers_posted? %>
          <% posted_message = "Unpost Answers" %>
        <% else %>
          <% posted_message = "Post Answers" %>
        <% end %>
        <%= button_to posted_message, post_answers_path, :class => "flat-button", 
                :method => :post, :confirm => "Are you sure you want to #{posted_message}" %>
      </li>
      <li>
        <%= button_to "Mail Out the Answers", email_answers_path,
                :class => "flat-button", :method => :post, 
                :confirm => "Mail out answers?" %>
      </li>
      <li>
        <%= link_to "Administrate Answers", admin_answers_path %>
      </li>
    </ul>
  </div>
</div>