config/routes.rb
Tq::Application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations"
  }  

  resources :users, :only => [:index, :edit, :update, :destroy]
  resources :questions
  resources :suggestions, :only => [:index, :create]
  resources :suggestions do
    post 'vote', to: 'suggestions#vote'
    post 'toggle_archive', to: 'suggestions#toggle_archive'
  end
  get '/about', to: 'static_pages#about'
  get '/admin_dashboard', to: 'admin_dashboard#dashboard'
  get '/admin_answers', to: 'answers#admin_answers'
  post '/email_question', to: 'admin_dashboard#email_question'
  post '/email_answers', to: 'admin_dashboard#email_answers'
  post '/post_answers', to: 'questions#release'
  get '/silly_title', to: 'sillytitles#new'
  get '/scoreboard', to: 'users#scoreboard'
  post '/reset_password', to: 'users#reset_password'

  resources :answers do
    post 'vote', to: 'answers#vote'
    resources :comments, :only => [:create, :destroy, :update]
  end
  resources :feed_items, :only => :update

  root :to => 'questions#today'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :stars
  has_many :comments

  validates :body, :user_id, :question_id, :presence => true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :admin_user, :only => [:admin_answers, :destroy]

  def new
    if current_user.answered_today?
      @answer = current_user.users_current_answer
    else
      @answer = Answer.new
    end
  end

  def admin_answers
    @answers = Question.todays_question.answers
  end

  def destroy
    Answer.find(params[:id]).destroy
    redirect_to admin_answers_path
  end

  def create
    if current_user.answers.create(params[:answer])
      current_user.score += 50
      current_user.legacy_score += 50
      current_user.save!
      current_user.maybe_generate_feed_item
      redirect_to root_url
    else
      redirect_to root_url
    end
  end

  def update
    current_user.users_current_answer.update_attributes(params[:answer])
    redirect_to root_url
  end

  def vote
    # It always costs the current user 5
    # points to vote either up or down.
    answer = Answer.find_by_id(params[:answer_id])
    if current_user.score >= 5
      if params[:score] == "up"
        answer.score += 5
        # I make sure the answer saves before updating user.
        if answer.save
          answer.user.legacy_score += 10
          answer.user.save!
        end
      elsif params[:score] == "down"
        answer.user.legacy_score -= 10
        answer.user.save!
        answer.score -= 5
        answer.save!
      end
      current_user.score -= 5
      current_user.legacy_score += 1
      current_user.save!
    end
    render :json => {
      answer_score: answer.score,
      user_score: current_user.score
    }
  end
end

app/views/answers/_new.html.erb
<%= form_for(current_user.users_current_answer,
    :html => { :class =>  'answer-form' }) do |f| %>

  <%= f.text_area :body %>
  <%= f.hidden_field :question_id, :value => Question.todays_question.id %>

  <%= f.submit "Answer", :class => "flat-button" %>

<% end %>

app/views/answers/_show.html.erb
<% @answers.each do |answer| %>
  <div class="user-answer">
    <div class="answer-header" style="background: <%=answer.user.color%>">
      <span><%= answer.user.username %></span>
      <% if current_user.provider == "facebook" && current_user.friends_with?(answer.user) %>
        <span class="fb-friend">
              Your friend.
        </span>
      <% end %>
        <% answer.user != current_user && current_user.score >= 5 ? vote_class = "show-vote" : vote_class = "hide-vote"%>
        <span class="answer-buttons <%= vote_class %>">
        <%= button_to "▲", answer_vote_path(answer_id: answer.id,
            score: "up"), remote: true, method: :post,
            form_class: "vote-form", class: "vote-button" %>
            <br />
            <span class="user-score" id="user<%= answer.user.id %>-score">
              <%=answer.score%>
            </span>
            <br />
        <%= button_to "▼", answer_vote_path(answer_id: answer.id,
            score: "down"), remote: true, method: :post,
            form_class: "vote-form", class: "vote-button" %>
        </span>        
        <br>
        <span class="user-title">
          <%= answer.user.title %>
        </span>

    </div>

    <div class="answer-body">
      <p>
        <%= auto_link(simple_format(answer.body),
          :tags => %w(br p) )%>
      </p>
    </div>

    <% commentstatus = answer.comments.empty? ? "" : "comments-on" %>

    <div class="comment-toggle <%= commentstatus %>">
      <span class="show-comments fake-link">
        <%=answer.comments.count %>
        <i class="icon-comment"></i>
      </span>
    </div>

    <div class="comments <%= commentstatus %>">
      <div class="comment-collection">
      <%= render :partial => 'questions/comment',
                 :collection => answer.comments %>
      </div>

      <%= form_for([answer, answer.comments.build],
          :remote => true, :class => "new_comment" ) do |f| %>

        <%= f.text_area :body, :placeholder => "Comment on #{answer.user.username}'s answer...", 
						:class => "comment-field" %>
        <%= f.submit "Add Comment", :disable_with => "Saving...", :class => "flat-button comment-button" %>
      <% end %>
      <span class="fake-link hide-comments">
        <%=answer.comments.count %>
        <i class="icon-comment-alt"></i>
      </span>
    </div>

  </div>
<% end %>

app/views/answers/_show_logged_out.html.erb
<% @answers.each do |answer| %>
  <div class="user-answer">
    <div class="answer-header" style="background: <%=answer.user.color%>">
      <span><%= answer.user.username %></span>
        <span class="answer-buttons">
            <br />
            <span class="user-score" id="user<%= answer.user.id %>-score">
              <%=answer.score%>
            </span>
            <br />
        </span>        
        <br>
        <span class="user-title">
          <%= answer.user.title %>
        </span>

    </div>

    <div class="answer-body">
      <p>
        <%= auto_link(simple_format(answer.body),
          :tags => %w(br p) )%>
      </p>
    </div>

    <% commentstatus = answer.comments.empty? ? "" : "comments-on" %>

    <div class="comment-toggle <%= commentstatus %>">
      <span class="show-comments fake-link">
        <%=answer.comments.count %>
        <i class="icon-comment"></i>
      </span>
    </div>

    <div class="comments <%= commentstatus %>">
      <div class="comment-collection">
      <%= render :partial => 'questions/comment',
                 :collection => answer.comments %>
      </div>

      <span class="fake-link hide-comments">
        <%=answer.comments.count %>
        <i class="icon-comment-alt"></i>
      </span>
    </div>

  </div>
<% end %>

app/views/answers/admin_answers.html.erb
<div class="row container bigbox">
  <div class="span4 left-span-content">
    <h1>Admin Answers!</h1>
  </div>

  <div class="span7">
    <% unless @answers.empty? %>
      <% @answers.each do |answer| %>
        <div class="user-answer">
          <div class="answer-header" style="background: <%=answer.user.color%>">
            <span><%= answer.user.username %>
              <span class="user-score" id="user<%= answer.user.id %>-score">
                <%=answer.score%> points.
              </span>
              <span class="answer-buttons">
              <%= button_to "+", answer_vote_path(answer_id: answer.id,
                  score: "up"), remote: true, method: :post,
                  form_class: "vote-form", class: "btn" %>

              <%= button_to "-", answer_vote_path(answer_id: answer.id,
                  score: "down"), remote: true, method: :post,
                  form_class: "vote-form", class: "btn" %>
              </span>
            </span>
          </div>

          <div class="answer-body">
            <p>
              <%= sanitize(simple_format(answer.body),
                :tags => %w(br p) )%>
            </p>
            <p>
              <%= link_to "Delete", answer, method: :delete,
                data: { confirm: "Really delete #{answer.body}?" } %>
            </p>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>
</div>