config/routes.rb
Tq::Application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations"
  }  

  resources :users, :only => [:index, :edit, :update, :destroy]
  resources :questions
  resources :suggestions, :only => [:index, :create]
  resources :suggestions do
    post 'vote', to: 'suggestions#vote'
    post 'toggle_archive', to: 'suggestions#toggle_archive'
  end
  get '/about', to: 'static_pages#about'
  get '/admin_dashboard', to: 'admin_dashboard#dashboard'
  get '/admin_answers', to: 'answers#admin_answers'
  post '/email_question', to: 'admin_dashboard#email_question'
  post '/email_answers', to: 'admin_dashboard#email_answers'
  post '/post_answers', to: 'questions#release'
  get '/silly_title', to: 'sillytitles#new'
  get '/scoreboard', to: 'users#scoreboard'
  post '/reset_password', to: 'users#reset_password'

  resources :answers do
    post 'vote', to: 'answers#vote'
    resources :comments, :only => [:create, :destroy, :update]
  end
  resources :feed_items, :only => :update

  root :to => 'questions#today'
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  validates :body, :user_id, :presence => true
  
  belongs_to :user
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  
  def index
    @suggestion = Suggestion.new
    @suggestions = Suggestion.where(:archived => false).order('score DESC').all
    @archived_suggestions = Suggestion.where(:archived => true).order('score DESC').all
  end
  
  def create
    if current_user.score >= 50
      suggestion = current_user.suggestions.create(params[:suggestion])
      if suggestion.save
        current_user.score -= 50
        current_user.save!
      end
      redirect_to suggestions_path
    else
      flash[:alert] = 'You don\'t have enough Internets to make a suggestion...'
      redirect_to suggestions_path
    end
  end
  
  def vote
    suggestion = Suggestion.find_by_id(params[:suggestion_id])
    if current_user.score >= 5
      if params[:score] == "up"
        suggestion.score += 5
        # I make sure the answer saves before updating user.
        if suggestion.save
          suggestion.user.legacy_score += 10
          suggestion.user.save!
        end
      else
        suggestion.score -= 5
        suggestion.save!
      end
      # Should eventually check if answer saves here too.
      # http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html
      current_user.score -= 5
      current_user.legacy_score += 1
      current_user.save!
    end
    render :json => {
      suggestion_score: suggestion.score,
      user_score: current_user.score
    }
  end
  
  def toggle_archive
    if current_user.admin?
      suggestion = Suggestion.find_by_id(params[:suggestion_id])
      suggestion.toggle!(:archived)
      redirect_to suggestions_path
    else
      redirect_to suggestions_path
    end
  end
end

app/views/suggestions/_new.html.erb
<div class="new-suggestion">
  <div class="suggestion-tip">It costs 50 Internets to create a suggestion. You can also use your Internets to vote on others' suggestions
  </div>
  <%= form_for @suggestion do |f| %>
  <%= f.text_area :body %>
  <%= f.submit "Suggest!", :class => "flat-button" %>
  <% end %>
</div>

app/views/suggestions/index.html.erb
<div class="row container bigbox">
  <div class="span4 left-span-content">

    <h1>Suggest a question!</h1>

    <span>And use your Internets to upvote other people's suggestions.
    They still have to pass the Rubber Helmet Test.</span>
    
    <span>If you have more than 50 Internets, you can make a suggestion.</span>

  </div>

  <div class="span7">
    <% if current_user.score >= 50 %>
    <%= render :partial => 'suggestions/new' %>
    <% end %>
    <br />
    <h1>New Suggestions</h1>
    <br />
    <% @suggestions.each do |suggestion| %>
      <div class ="suggestion" style="background: <%=suggestion.user.color%>"><%= suggestion.user.username %> suggested:
      <% suggestion.user != current_user && current_user.score >= 5 ? sugg_class = "show-vote" : sugg_class = "hide-vote"%>
      <span class="suggestion-buttons <%= sugg_class %>">
      <%= button_to "▲", suggestion_vote_path(suggestion_id: suggestion.id,
          score: "up"), remote: true, method: :post,
          form_class: "vote-form", class: "vote-button" %>
          <br />      
          <span class="suggestion-score" id="user<%= suggestion.user.id %>-score">
            <%=suggestion.score%>
          </span>
          <br />
      <%= button_to "▼", suggestion_vote_path(suggestion_id: suggestion.id,
          score: "down"), remote: true, method: :post,
          form_class: "vote-form", class: "vote-button" %>
      </span>
      <% if current_user.admin? %>
        <h6>
        <%= link_to "Toggle Archived", suggestion_toggle_archive_path(suggestion), method: :post %>
        </h6>
      <% end %>
      <div class="suggestion-body"><%= suggestion.body %></div>
      </div>
    <% end %>
    
    <br />
    <h1>Archived Suggestions</h1>
    <br />
    
    <% @archived_suggestions.each do |suggestion| %>
      <div class ="suggestion" style="background: <%=suggestion.user.color%>"><%= suggestion.user.username %> suggested:
      <span class="suggestion-buttons hide-vote">    
          <span class="suggestion-score" id="user<%= suggestion.user.id %>-score">
            <%=suggestion.score%>
          </span>
          <br />
      </span>
      <% if current_user.admin? %>
        <h6>
          <%= link_to "Toggle Archived", suggestion_toggle_archive_path(suggestion), method: :post %>
        </h6>
      <% end %>
      <div class="suggestion-body"><%= suggestion.body %></div>
      </div>
    <% end %>
  </div>
</div>