config/routes.rb
Tq::Application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks", 
    :registrations => "registrations"
  }  

  resources :users, :only => [:index, :edit, :update, :destroy]
  resources :questions
  resources :suggestions, :only => [:index, :create]
  resources :suggestions do
    post 'vote', to: 'suggestions#vote'
    post 'toggle_archive', to: 'suggestions#toggle_archive'
  end
  get '/about', to: 'static_pages#about'
  get '/admin_dashboard', to: 'admin_dashboard#dashboard'
  get '/admin_answers', to: 'answers#admin_answers'
  post '/email_question', to: 'admin_dashboard#email_question'
  post '/email_answers', to: 'admin_dashboard#email_answers'
  post '/post_answers', to: 'questions#release'
  get '/silly_title', to: 'sillytitles#new'
  get '/scoreboard', to: 'users#scoreboard'
  post '/reset_password', to: 'users#reset_password'

  resources :answers do
    post 'vote', to: 'answers#vote'
    resources :comments, :only => [:create, :destroy, :update]
  end
  resources :feed_items, :only => :update

  root :to => 'questions#today'
end

app/views/layouts/_greeting.html.erb
<% if user_signed_in? %>
  <div class="container greeting bigbox" style="background: <%= current_user.color %>">
    <div class="span12">
      <h1>Hi, <%= current_user.username %>.</h1>
        <span class="greeting_info">
          <% if current_user.score > 0 %>
            You have
            <span id="current_user_score">
              <%= current_user.score %>
            </span>
            Internets.
          <% else %>
            Answer questions to get more points.
          <% end %>
        </span>
    </div>
  </div>
<% else %>
  <div class="container greeting bigbox">
    <div class="span12">
      <h1 style="color: white"> Hi! </h1>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.haml
%header.navbar.navbar-inverse
  .navbar-inner
    .container-fluid.nav-container
      %ul
        %li.brand= link_to "TQ: #{TqHelper.new_tq}", '/'

      %ul.nav.navbar-nav.pull-right
        - if user_signed_in?
          %li=link_to "Suggestions", suggestions_path
          %li=link_to "Scoreboard", scoreboard_path
          %li=link_to "About", about_path
          %li=link_to "Today's Question", new_question_path
          %li=link_to "Archives", questions_path

          - if current_user && current_user.admin?
            %li= link_to '<i class="icon-fighter-jet icon-large"></i>'.html_safe, admin_dashboard_path

            %li= link_to '<i class="icon-cog icon-large"></i>'.html_safe, edit_user_registration_path
            %li.dropdown.noti-container
              %a{:href=> "#", :class=> "dropdown-toggle", :data => {:toggle=>"dropdown"} }
                %i.icon-envelope-alt.icon-large
                  - if current_user.unread_item_count > 0
                    %p.noti-badge= current_user.unread_item_count

                %ul.dropdown-menu.dropdown-flat
                  - current_user.feed_items.each do | feeditem |
                    %li{:class => "read<%= feeditem.read %>"}
                      = link_to "#{feeditem.body}", feeditem, :method => :put, :class => "dropdown-item"

          %li= link_to '<i class="icon-signout icon-large"></i>'.html_safe, destroy_user_session_path,
                :method => :delete
        - else
          %li= link_to "Archives", questions_path
          %li= link_to "Log in", new_user_session_path
          %li= link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TQ</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <%= render 'layouts/greeting' %>

    <% unless notice.nil? && alert.nil? %>
      <div class="container alerts">
        <p class="notice close">
          <%= notice %>
        </p>
        <p class="alert close">
          <%= alert %>
        </p>
      </div>
    <% end %>

  <%= yield %>

</body>
</html>